version: '3.8'

services:
  # ERC-8004 Trustless Agent for Phala Cloud TEE deployment
  app:
    image: erc-8004-ex-phala:erc8004-phala
    container_name: erc8004-trustless-agent
    
    # Environment configuration
    environment:
      - AGENT_TYPE=${AGENT_TYPE:-server}
      - CONTAINER_MODE=true
      - NODE_ENV=production
      - TEE_MODE=production
      - RPC_URL=${RPC_URL}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - CONTRACT_ADDRESS=${CONTRACT_ADDRESS}
      - HEALTHCHECK_INTERVAL=30000
      - GRANT_SUDO=yes  # Allows development access in Phala Cloud
    
    # TEE socket mounting for attestation
    volumes:
      - /var/run/dstack.sock:/var/run/dstack.sock  # Phala Cloud TEE socket
    
    # Network configuration
    ports:
      - "8080:8080"  # Agent API endpoint
    
    # Run as root for development (adjust for production)
    user: root
    
    # Start command using Flox activate entrypoint
    command: ["-c", "python -m agents.server_agent"]
    
    # Restart policy
    restart: unless-stopped
    
    # Health check using Flox activate
    healthcheck:
      test: ["CMD", "/nix/store/ic29r7ab9lpbhan7icxkb096qkmhzwzc-environment-develop/activate", "-c", "python -c 'import sys; sys.exit(0)'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s